### PR TITLE
Add basic screenshot cropping

### PR DESCRIPTION
**Pull request by Jestre**
This should enable basic screenshot cropping, but requires Pillow.

Config variables:
do_crop (true|false) - Crop the screenshot?  Perhaps the default should be false?
crop_width, crop_height - Basically coordinates for the bottom right corner.  Using 816 should crop off the data panel and flights table.

My editor also chopped off extraneous whitespace at the ends of lines, so not sure if that is an issue.

### CODE REVIEW

**Comment by Romeo-Golf** [comment]
Although I havent run/tested it, the code looks reasonable to me.. :)

Also would you mind posting a screenshot of the output?

Thanks..

**Comment by Jestre** [comment]
The screenshot will look like the recent posts on https://twitter.com/aboveraleigh just minus the inset data box in the lower right corner.

**Comment by kevinabrandon** [comment]
Looks good to me, only thing I would do is add a couple more config vars `crop_x` and `crop_y` and set them to zero.  Then for the actual crop you could do: `im = im.crop((crop_x, crop_y, crop_width, crop_height))`.

That way if people wanted they could crop it a bit tighter to remove the maps buttons.

**Comment by Jestre** [comment]
How did I know that was coming? :)  Added and pushed.

**Comment by kevinabrandon** [comment]
Awesome thanks!

**Comment by Romeo-Golf** [comment]
yeah looks great, the revised aspect ratio defiantly helps improve readability in the default twitter layout where the tweets seems to get about 1/4 of the screen width :)

**Pull request merged**
